### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by Cisco-the-wayword** [jlvFlores/catalog-of-my-things#32]
https://github.com/jlvFlores/catalog-of-my-things/projects/1

There are three members of this team
@Cisco-the-wayword is working on the tasks assigned to #Team member 1
@jlvFlores is working on the tasks assigned to #Team member 2
@haftamuDesta is working on the tasks assigned to #Team member 3

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @jlvFlores, @Cisco-the-wayword, and @haftamudesta👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] Most of the task cards are missing descriptions. Please make sure all task cards have descriptive descriptions as requested in the project requirements.
![image](https://github.com/jlvFlores/catalog-of-my-things/assets/83803414/636808a1-3ccd-4ebe-995f-998fa06aad99)

- [ ] Please make sure all task cards have the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of estimated work. Currently, no task card has a points prefix.

- [ ] Please make sure all task cards have assigned team members as requested in the project requirements. Currently, some task cards are missing assigned members. You should divide the tasks among team members equally based on the point prefix.
![image](https://github.com/jlvFlores/catalog-of-my-things/assets/83803414/5d705f7e-4e58-4c53-8d86-151cf187f656)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by abdulhamiid** [comment]
Hi Team 👋, 

## STATUS: APPROVED 😃

In my opinion, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
